# backend/open_webui/routers/crawl.py
from fastapi import APIRouter, Query, HTTPException
from typing import List, Dict, Any

# Crawl4AI
from crawl4ai import AsyncWebCrawler, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
# DefaultMarkdownGenerator ensures that the result object contains a .markdown field,
# making it convenient for the frontend to render directly or pass to AI summarization.
# Reference: result.markdown is automatically generated by markdown_generator
# https://docs.crawl4ai.com/core/markdown-generation/

router = APIRouter()

def _dedup(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Remove duplicate crawl results based on URL and markdown hash."""
    seen = set()
    out = []
    for it in items:
        key = (it.get("url") or "", hash(it.get("markdown") or ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(it)
    return out

@router.get("/api/crawl")
async def crawl(
    urls: List[str] = Query(..., alias="urls", description="Pass multiple `?urls=` to add multiple URLs"),
):
    if not urls:
        raise HTTPException(400, "At least one urls= is required")

    # Basic sanitization & filter out invalid schemes
    clean_urls = []
    for u in urls:
        if not u:
            continue
        u = u.strip()
        if u.startswith("http://") or u.startswith("https://"):
            clean_urls.append(u)
    if not clean_urls:
        raise HTTPException(400, "No valid http(s) URLs provided")

    # Ensure results include the markdown field
    run_cfg = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
    )

    # Single-instance concurrency: arun_many will run the crawl tasks in parallel internally
    # Docs: arun_many(urls, config=...) is responsible for multi-URL concurrent crawling
    # https://docs.crawl4ai.com/api/async-webcrawler/
    async with AsyncWebCrawler() as crawler:
        results = await crawler.arun_many(clean_urls, config=run_cfg)

    payload = []
    for r in results:
        url = getattr(r, "url", "") or ""
        title = getattr(r, "title", "") or ""
        markdown = getattr(r, "markdown", "") or ""
        success = bool(getattr(r, "success", False))
        error = getattr(r, "error_message", None)

        payload.append({
            "url": url,
            "title": title,
            "markdown": markdown,
            "success": success,
            "error": error
        })

    return _dedup(payload)
